version: 1.0.{build}
branches:
  only:
  - master
  - RC_1_0
os: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - variant: test_debug
    python_package: 1
    linkflags: '"/LIBPATH:C:\\openssl-1.0.1p-vs2013\\lib"'
    include: '"c:\\openssl-1.0.1p-vs2013\\include"'
  - variant: test_barebones
    linkflags: '"/LIBPATH:C:\\openssl-1.0.1p-vs2013\\lib"'
    include: '"c:\\openssl-1.0.1p-vs2013\\include"'
  - variant: test_release
    linkflags: '"/LIBPATH:C:\\openssl-1.0.1p-vs2013\\lib"'
    include: '"c:\\openssl-1.0.1p-vs2013\\include"'

install:
- set ROOT_DIRECTORY=%CD%
- cd %ROOT_DIRECTORY%
- if not exist openssl-1.0.1p-vs2013.7z (
    echo downloading openssl-2013
    & appveyor DownloadFile "http://www.npcglib.org/~stathis/downloads/openssl-1.0.1p-vs2013.7z"
  )
- 7z x -oc:\ -aoa openssl-1.0.1p-vs2013.7z > nul
- copy c:\openssl-1.0.1p-vs2013\lib64\ssleay32MT.lib c:\openssl-1.0.1p-vs2013\lib64\ssleay32.lib
- copy c:\openssl-1.0.1p-vs2013\lib64\libeay32MT.lib c:\openssl-1.0.1p-vs2013\lib64\libeay32.lib
- copy c:\openssl-1.0.1p-vs2013\lib\ssleay32MT.lib c:\openssl-1.0.1p-vs2013\lib\ssleay32.lib
- copy c:\openssl-1.0.1p-vs2013\lib\libeay32MT.lib c:\openssl-1.0.1p-vs2013\lib\libeay32.lib
- cd %ROOT_DIRECTORY%
- set BOOST_ROOT=c:\Libraries\boost
- set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
- echo %BOOST_ROOT%
- echo %BOOST_BUILD_PATH%
- set PATH=%PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86
- 'echo using msvc : 12.0 ; >>%HOMEDRIVE%%HOMEPATH%/user-config.jam'
- 'echo using msvc : 9.0 ; >>%HOMEDRIVE%%HOMEPATH%/user-config.jam'
- type %HOMEDRIVE%%HOMEPATH%\user-config.jam
- cd %ROOT_DIRECTORY%
- python --version
- echo %ROOT_DIRECTORY%
- cd %BOOST_BUILD_PATH%\src\engine
- build.bat >nul
- cd %ROOT_DIRECTORY%
cache:
- openssl-1.0.1p-vs2013.7z
build_script:
- cd %ROOT_DIRECTORY%\examples
- b2.exe --hash -j2 boost=source msvc-12.0 variant=%variant% linkflags=%linkflags% include=%include% link=shared
- cd %ROOT_DIRECTORY%\bindings\python
- b2.exe --hash -j2 boost=source msvc-12.0 stage_module install-dependencies=on variant=%variant% libtorrent-link=shared linkflags=%linkflags% include=%include%
- python test.py
- if defined python_package ( python setup.py --bjam bdist_msi )
test_script:
- cd %ROOT_DIRECTORY%\test
- b2.exe --hash -j2 boost=source address-model=32 msvc-12.0 variant=%variant% link=shared linkflags=%linkflags% include=%include% ci-tests

artifacts:
  - path: bindings\python\dist\*.msi
    name: python-binding-win32

